<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron">
    <h1 class="display-4">Format XML</h1>
    <hr class="my-4">
</div>

<?php
if (!empty($xml)) {
    ?>
    <div class="jumbotron">
        <h4>Formatted XML:</h4>
        <textarea class="form-control" rows="8" readonly id="textToCopy"><?= $xml; ?></textarea>
        <div class="bd-clipboard">
            <button class="btn-clipboard" data-original-title="Copy to clipboard" onclick="copyTextArea()">Copy</button>
        </div>
    </div>
<?php
}
if (!empty($error)) {
    ?>
    <div class="jumbotron">
        <h4>Error:</h4>
        <?= $error; ?>
    </div>
<?php } ?>

<div>
    <?php
    // This provides a default CSS class and placeholder text for the artist element:
    $xml = $form->get('xml');
    $xml->setAttribute('class', 'form-control');
    $xml->setAttribute('placeholder', 'XML');

    // This provides CSS classes for the submit button:
    $submit = $form->get('submit');
    $submit->setAttribute('class', 'btn btn-primary');

    $form->setAttribute('action', $this->url('formatXml', ['action' => 'index']));
    $form->prepare();

    echo $this->form()->openTag($form);
    ?>
    <?php // Wrap the elements in divs marked as form groups, and render the
    // label, element, and errors separately within ?>
    <div class="form-group">
        <?= $this->formLabel($xml) ?>
        <?= $this->formElement($xml) ?>
        <?= $this->formElementErrors()->render($xml, ['class' => 'help-block']) ?>
    </div>

    <?php
    echo $this->formSubmit($submit);
    echo $this->form()->closeTag();
    ?>
</div>
