<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron">
    <h1 class="display-5">Welcome to Franco's PHP Playground</h1>

    <p>
        Congratulations! You are the choosen one.
    </p>
</div>

<div class="card-deck">
    <div class="card">
        <h2 class="card-header">Format SQL</h2>
        <div class="card-body">
            <p>
                Pretty prints a SQL query
            </p>

            <a class="btn btn-primary" href="<?= $this->url('formatSql') ?>">Format SQL &raquo;</a>
        </div>
    </div>

    <div class="card">
        <h2 class="card-header">Format JSON</h2>
        <div class="card-body">
            <p>
                Pretty print a JSON object
            </p>

            <a class="btn btn-primary" href="<?= $this->url('formatJson') ?>">Format JSON &raquo;</a>
        </div>
    </div>

    <div class="card">
        <h2 class="card-header">Format XML</h2>
        <div class="card-body">
            <p>
                Pretty print a XML document
            </p>

            <a class="btn btn-primary" href="<?= $this->url('formatXml') ?>">Format Xml &raquo;</a>
        </div>
    </div>
</div>

<hr class="my-4">

<div class="card-deck">
    <div class="card">
        <h2 class="card-header">PHP Array String To JSON</h2>
        <div class="card-body">
            <p>
                Convert a PHP array string to json. Paste array string from config file to convert to JSON
            </p>

            <a class="btn btn-primary" href="<?= $this->url('arrayToJson') ?>">PHP Array To JSON &raquo;</a>
        </div>
    </div>
</div>
